apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
  labels:
    app: kyc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
    spec:
      containers:
        - name: kyc-service
          image: 325779841724.dkr.ecr.ap-south-1.amazonaws.com/kfinfund-kyc-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/kfinfund_kyc"
            - name: JWT_SECRET
              value: "kfinfund_secret_key_2026"
            - name: PORT
              value: "3002"
            - name: POSTGRES_USER_URL
              value: postgresql://postgres:postgres123@postgres-service:5432/kfinfund_users
            - name: SANDBOX_API_KEY
              value: key_live_d2880acf4af34467b1bac282327c2e72
            - name: SANDBOX_API_SECRET
              value: secret_live_d7ce65299b5340d993113f734c9d1544
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-service
spec:
  selector:
    app: kyc-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP